# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0002_auto_20161118_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 18, 12, 24, 8, 807895, tzinfo=utc), editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 18, 12, 24, 8, 807895, tzinfo=utc), editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
